import { CashflowTransactionSchema, type CashflowTransaction } from "@/lib/cashflow/schema";

/**
 * Starter data so the transactions list/detail pages aren't empty on first
 * load. Adapted from real rows in the clinic's sample CSV export (July 1-5
 * 2026), chosen to cover a range of cases: different dentists and payment
 * types, a Reservation (no dentist/visit type), a zero-payment procedure,
 * and a high-value card transaction with merchant fee + withholding tax.
 *
 * Remove this once the app is seeded from a real import or a database —
 * it exists only so the UI has something to show before either exists.
 * Passed through the schema so it's held to the same validation as any
 * other transaction.
 */
const RAW_SEED_TRANSACTIONS = [
  {
    id: "20260701-001-1",
    date: "2026-07-01",
    visitId: "20260701-001",
    patientName: "Urbino, Abegail",
    transactionType: "Visit",
    visitType: "RETURNING",
    dentist: "BANDAYREL",
    procedure: "Ortho Adj",
    paymentType: "Cash",
    amountPaid: 1000,
    vatExclusive: 1000,
    vatAmount: 0,
    month: "July",
    year: 2026,
    invoiceNumber: "",
    remarks: "",
    merchantFee: 0,
    withholdingTax: 0,
    netCollection: 1000,
  },
  {
    id: "20260701-002-1",
    date: "2026-07-01",
    visitId: "20260701-002",
    patientName: "Agcaoili, Elaine Mae",
    transactionType: "Visit",
    visitType: "NEW",
    dentist: "BANAWA",
    procedure: "Consultation",
    paymentType: "Maxicare",
    amountPaid: 150,
    vatExclusive: 150,
    vatAmount: 0,
    month: "July",
    year: 2026,
    invoiceNumber: "",
    remarks: "Covered by Maxicare Consultation",
    merchantFee: 0,
    withholdingTax: 0,
    netCollection: 150,
  },
  {
    id: "20260701-003-1",
    date: "2026-07-01",
    visitId: "20260701-003",
    patientName: "Vigare, Jhonalie",
    transactionType: "Visit",
    visitType: "RETURNING",
    dentist: "TEOPE",
    procedure: "Backjob Resto",
    paymentType: "",
    amountPaid: 0,
    vatExclusive: 0,
    vatAmount: 0,
    month: "July",
    year: 2026,
    invoiceNumber: "",
    remarks: "",
    merchantFee: 0,
    withholdingTax: 0,
    netCollection: 0,
  },
  {
    id: "20260701-009-1",
    date: "2026-07-01",
    visitId: "20260701-009",
    patientName: "Trogo, Alynna",
    transactionType: "Visit",
    visitType: "NEW",
    dentist: "WALK IN",
    procedure: "Panoramic Xray w/ Hard Copy",
    paymentType: "GCash",
    amountPaid: 1250,
    vatExclusive: 1116.07,
    vatAmount: 133.93,
    month: "July",
    year: 2026,
    invoiceNumber: "3662",
    remarks: "Ref no. 2042419692282",
    merchantFee: 0,
    withholdingTax: 0,
    netCollection: 1116.07,
  },
  {
    id: "20260701-012-2",
    date: "2026-07-01",
    visitId: "20260701-012",
    patientName: "Alvarado, Ma. Lourdes Sarah",
    transactionType: "Visit",
    visitType: "RETURNING",
    dentist: "BANAWA",
    procedure: "PF(2)",
    paymentType: "POS (GHL) - CREDIT",
    amountPaid: 2400,
    vatExclusive: 2142.86,
    vatAmount: 257.14,
    month: "July",
    year: 2026,
    invoiceNumber: "3665",
    remarks: "CREDIT CARD APPROVAL CODE: 091318",
    merchantFee: 67.2,
    withholdingTax: 12,
    netCollection: 2063.66,
  },
  {
    id: "RES-20260701-001-1",
    date: "2026-07-01",
    visitId: "RES-20260701-001",
    patientName: "Alvarado, Ma. Lourdes Sarah",
    transactionType: "Reservation",
    visitType: "",
    dentist: "",
    procedure: "Reservation Fee",
    paymentType: "GCash",
    amountPaid: 150,
    vatExclusive: 150,
    vatAmount: 0,
    month: "July",
    year: 2026,
    invoiceNumber: "",
    remarks: "Ref no. 9042406839042",
    merchantFee: 0,
    withholdingTax: 0,
    netCollection: 150,
  },
  {
    id: "20260705-006-1",
    date: "2026-07-05",
    visitId: "20260705-006",
    patientName: "Antonio, Andrei",
    transactionType: "Visit",
    visitType: "RETURNING",
    dentist: "K. ROLDAN",
    procedure: "Ortho Install(Package5) FULL PAYMENT + OP(Moderate) w/5,000 Discount Ortho Package",
    paymentType: "POS (GHL) - CREDIT",
    amountPaid: 66615,
    vatExclusive: 59477.68,
    vatAmount: 7137.32,
    month: "July",
    year: 2026,
    invoiceNumber: "3697",
    remarks: "CREDIT CARD APPROVAL CODE: 085964; 5,000 discount for full payment",
    merchantFee: 1865.22,
    withholdingTax: 333.075,
    netCollection: 57279.38,
  },
];

export const SEED_TRANSACTIONS: CashflowTransaction[] = RAW_SEED_TRANSACTIONS.map((row) =>
  CashflowTransactionSchema.parse(row),
);
